image: node:16.5.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - docs/package-lock.json
      prefix: npm
    paths:
      - docs/node_modules/
  script:
    - npm install
    - npm run build
    - cp -a docs/dist/. public/
  artifacts:
    paths:
      - docs/public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    
